name: Build Hunyuan3D
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build Docker image
        run: docker build -t fiscaliabo/hunyuan3d:latest .
      
      - name: Login and Push
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u fiscaliabo --password-stdin && docker push fiscaliabo/hunyuan3d:latest
