name: Docker Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build --no-cache -t fiscaliabo/hunyuan3d:v6 .
      
      - name: Login
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u fiscaliabo --password-stdin
      
      - name: Push
        run: docker push fiscaliabo/hunyuan3d:v6
